"""Build data/crowd_data.js from the raw SurveyMonkey export.

Run manually:  uv run scripts/build_crowd_data.py

Input:  data/Spot the Fake Smile v.3.csv  (gitignored; contains respondent IP
        addresses — must never be committed)
Output: data/crowd_data.js  (aggregate statistics only — no per-respondent
        rows, no identifiers — safe to commit)

Only respondents who answered all 20 videos are counted, so every figure in
the output (mean, distribution, per-video % Genuine, crowd Brier score) comes
from the same group.
"""

import csv
import json
import re
from datetime import date
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
RAW_CSV = ROOT / "data" / "Spot the Fake Smile v.3.csv"
VIDEOS_JS = ROOT / "data" / "videos.js"
OUT_JS = ROOT / "data" / "crowd_data.js"

# The export has two header rows. The 20 answers are (Genuine, Fake) column
# pairs starting here, in the same order as data/videos.js.
FIRST_ANSWER_COL = 30
N_VIDEOS = 20


def load_answer_key():
    text = VIDEOS_JS.read_text(encoding="utf-8")
    ids = re.findall(r'id: "(v\d+)"', text)
    key = re.findall(r'correctAnswer: "([GF])"', text)
    if len(ids) != N_VIDEOS or len(key) != N_VIDEOS:
        raise SystemExit(f"Expected {N_VIDEOS} videos in {VIDEOS_JS}, found {len(ids)}/{len(key)}")
    return ids, key


def read_answers(row):
    """Return the 20 answers as "G"/"F", or None for an unanswered video."""
    answers = []
    for i in range(N_VIDEOS):
        genuine = row[FIRST_ANSWER_COL + 2 * i].strip()
        fake = row[FIRST_ANSWER_COL + 2 * i + 1].strip()
        answers.append("G" if genuine else "F" if fake else None)
    return answers


def main():
    ids, key = load_answer_key()

    n_complete = 0
    genuine_votes = [0] * N_VIDEOS
    distribution = [0] * (N_VIDEOS + 1)

    with RAW_CSV.open(encoding="utf-8-sig", errors="replace", newline="") as f:
        reader = csv.reader(f)
        next(reader)
        next(reader)
        for row in reader:
            answers = read_answers(row)
            if not all(answers):
                continue
            n_complete += 1
            distribution[sum(a == k for a, k in zip(answers, key))] += 1
            for i, a in enumerate(answers):
                genuine_votes[i] += a == "G"

    pct_genuine = [v / n_complete for v in genuine_votes]
    mean_correct = sum(score * n for score, n in enumerate(distribution)) / n_complete
    majority_correct = sum((p > 0.5) == (k == "G") for p, k in zip(pct_genuine, key))
    crowd_brier = sum((p - (k == "G")) ** 2 for p, k in zip(pct_genuine, key)) / N_VIDEOS

    crowd = {
        "source": "Spot the Fake Smile v.3 (SurveyMonkey), respondents who answered all 20 videos",
        "nComplete": n_complete,
        "meanCorrect": round(mean_correct, 4),
        "scoreDistribution": distribution,
        "majorityCorrect": majority_correct,
        "crowdBrier": round(crowd_brier, 4),
        "perVideo": [{"id": vid, "pctGenuine": round(p, 4)} for vid, p in zip(ids, pct_genuine)],
    }

    OUT_JS.write_text(
        "// GENERATED by scripts/build_crowd_data.py — do not edit by hand.\n"
        f"// Built {date.today().isoformat()}. Aggregate statistics only: no per-respondent\n"
        "// rows and no identifiers. pctGenuine is a 0-1 fraction.\n"
        f"export const CROWD = {json.dumps(crowd, indent=2)};\n",
        encoding="utf-8",
    )

    print(f"Wrote {OUT_JS.relative_to(ROOT)} ({OUT_JS.stat().st_size} bytes)")
    print(f"  complete respondents: {n_complete}")
    print(f"  mean correct: {mean_correct:.2f} / {N_VIDEOS}")
    print(f"  majority vote correct: {majority_correct} / {N_VIDEOS}")
    print(f"  crowd Brier: {crowd_brier:.4f}")


if __name__ == "__main__":
    main()
